package my_enum;

public enum ERROR_TYPE {
    PLACEHOLDER,
    UNDECLARED_VARIABLE,
    UNDEFINED_FUNCTION,
    REDEFINED_VARIABLE,
    REDEFINED_FUNCTION,
    INCOMPATIBLE_ASSIGN,
    INCOMPATIBLE_OPERATION,
    INCOMPATIBLE_RETURN_VALUE,
    INCOMPATIBLE_PARAMETERS,
    VARIABLE_NOT_ADDRESSABLE,
    VARIABLE_NOT_CALLABLE,
    ASSIGN_TO_FUNCTION
}
